[package]
name = "d3-retail"
version = "0.1.0"
edition = "2021"

[dependencies]
d3-core = { path = "../d3-core" }
log = "0.4.21"
bitflags = "2.5.0"
once_cell = "1.20.2"
tinyrand = "0.5.0"
anyhow = "1.0.97"
